# Generated by Django 6.1 on 2026-08-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="image",
            field=models.FileField(
                blank=True,
                help_text="Optional uploaded vehicle image.",
                upload_to="vehicles/",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Optional external image URL if no upload is available.",
            ),
        ),
    ]
